name: au3

on: 
 push:
   paths-ignore:
     - '.github/**'
     - '!.github/workflows/**'
     - '*.md'

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Install Autoit
      run: |
           Invoke-WebRequest -Uri https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe -OutFile autoit-v3-setup.exe
           ./autoit-v3-setup.exe /S
           Start-Sleep -s 10
    - name: Checkout repo
      run: |
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe
           git clone https://github.com/heshanu3d/TeleportHackOnVanilla
    - name: Install Full Editor tools
      run: |
           Invoke-WebRequest -Uri https://www.autoitscript.com/cgi-bin/getfile.pl?../autoit3/scite/download/SciTE4AutoIt3.exe -OutFile SciTE4AutoIt3.exe
           ./SciTE4AutoIt3.exe /S
           Start-Sleep -s 10 
    - name: Wrap Code
      run: |
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe\TeleportHackOnVanilla
           ../../AutoIt3.exe "C:\Program Files (x86)\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3" /NoStatus /prod /in "C:\Program Files (x86)\AutoIt3\Aut2Exe\TeleportHackOnVanilla\main1.12.1.au3"
           Start-Sleep -s 10
           ../../AutoIt3.exe "C:\Program Files (x86)\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3" /NoStatus /prod /in "C:\Program Files (x86)\AutoIt3\Aut2Exe\TeleportHackOnVanilla\main1.12.3.au3"
           Start-Sleep -s 10
           ../../AutoIt3.exe "C:\Program Files (x86)\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3" /NoStatus /prod /in "C:\Program Files (x86)\AutoIt3\Aut2Exe\TeleportHackOnVanilla\main3.3.5.au3"
           Start-Sleep -s 10
    - name: Rename and Aggregate Files
      run: |
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe
           mkdir build
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe\TeleportHackOnVanilla
           $ver= git describe --abbrev=0 --tags
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe\TeleportHackOnVanilla
           Move-Item "main1.12.1.exe" C:\"Program Files (x86)"\AutoIt3\Aut2Exe\build
           Move-Item "main1.12.3.exe" C:\"Program Files (x86)"\AutoIt3\Aut2Exe\build
           Move-Item "main3.3.5.exe" C:\"Program Files (x86)"\AutoIt3\Aut2Exe\build
           Move-Item "favlist.fav" C:\"Program Files (x86)"\AutoIt3\Aut2Exe\build
           cd C:\"Program Files (x86)"\AutoIt3\Aut2Exe
           cd build
           Rename-Item -Path "main1.12.1.exe" -NewName Teleportors-1.12.1-$ver.exe
           Rename-Item -Path "main1.12.3.exe" -NewName Teleportors-1.12.3-$ver.exe
           Rename-Item -Path "main3.3.5.exe" -NewName Teleportors-3.3.5-$ver.exe
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
       name: TeleportOnVanilla
       path: C:\Program Files (x86)\AutoIt3\Aut2Exe\build
       if-no-files-found: error
